Add GitHub Action Workflow for "dashboard-react-controls" Repository
pinis-gini-apps/dashboard-react-controls pull request #11
Opened 2024-09-02 08:14 UTC by pinis-gini-apps

Jira: https://iguazio.atlassian.net/issues/ML-7452?filter=-1

2024-09-02 14:12 UTC, mavdryk requested changes

2024-09-02 14:12 UTC, mavdryk commented on .github/workflows/ci.yaml
> +      - '[0-9]+.[0-9]+.[0-9]'          # Matches branches like '1.2.3'
the `+` sign is missing at the end

2024-09-02 14:12 UTC, mavdryk commented on .github/workflows/ci.yaml
> +      - '[0-9]+.[0-9]+.[0-9]'          # Matches branches like '1.2.3'
the same for `ui` repository

2024-09-03 05:37 UTC, pinis-gini-apps commented on .github/workflows/ci.yaml
> +      - '[0-9]+.[0-9]+.[0-9]'          # Matches branches like '1.2.3'
@mavdryk done.

2024-09-09 11:45 UTC, mavdryk approved these changes

2024-09-10 06:12 UTC, closed without merging